# https://developers.cloudflare.com/workers/wrangler/configuration

name = "sources"
compatibility_date = "2025-12-18"

compatibility_flags = [
	"nodejs_compat"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB_Sources" # i.e. available in your Worker on env.DB
database_name = "Sources.2025-12-18"
database_id = "1c094c81-ca66-45f4-af84-7e8fd1a4b9da"
