# https://developers.cloudflare.com/workers/wrangler/configuration

name = "sources"
compatibility_date = "2026-02-06"

compatibility_flags = [
	"nodejs_compat"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB_Sources" # i.e. available in your Worker on env.DB
database_name = "Sources_2026-01-29"
database_id = "305c578d-dc0a-46ff-8ae1-e54f92afd5e8"
